### ISSUE TITLE
Links | min hjemmeside

### ISSUE THREAD

**Issue by tinsir888** [tinsir888/tinsir888.github.io-gittalk#3]
https://tinsir888.github.io/link/ 

 This site is under construction. Diese Seite befindet sich im Aufbau.

**Comment by tinsir888** [comment]
Welcome to submit a friend link application!

You need to provide:

- Nickname
- Blog URL
- Avatar link
- Description

----

Willkommen zur Einreichung einer Freundeslink-Anfrage!

Sie müssen folgende Informationen angeben:

- Spitzname
- Blog-URL
- Avatar-Link
- Beschreibung

----

欢迎提出友链申请！

您需要提供：

- 昵称
- 博客网址
- 头像链接
- 个性签名或描述

**Comment by tinsir888** [comment]
本博客相关信息：
```yml
name: tinsir888's blog
link: https://tinsir888.github.io
avartar: https://avatars.githubusercontent.com/u/30094892?v=4
descr: Ηλύσια Πεδία ;-)
```
